### ISSUE TITLE
Cant access the web app

### ISSUE THREAD

**Issue by jimbrew** [getvivekv/graylog-ha-azure-aks#1]
Hello I have followed your [tutorial](https://blog.vivekv.com/setup-scalable-graylog-on-azure-kubernetes-aks-with-private-ip-and-nginx-ingress-controller.html) but I cannot seem to access the web frontend. Do I need to configure anymore rules?

At the moment I am just setting to HTTP will deal with SSL later. But all I want to do is access the website and send a log via the ports mention, in this case 30010.

My `internal-ingress.yaml` just updated the IP to a free one on the load balancer.

This is my `graylog-values.yaml` file:
```
graylog:
  image:
    repository: graylog/graylog
    tag: 4.2.6
  input:
    udp:
      service:
        type: NodePort
      ports:
        - name: getlf-30010-udp
          port: 30010
          nodePort: 30010
  service:
    type: ClusterIP
    port: 9000
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx-internal
    enabled: true
    hosts:
      - <myurl>
  rootPassword: <strongpassword>
  elasticsearch:
    version: 7
    hosts: http://elasticsearch.graylog.svc.cluster.local:9200
  mongodb:
    uri: mongodb://mongodb-0.mongodb-headless.graylog.svc.cluster.local:27017/graylog?replicaSet=rs0
  persistence:
    storageClass: custom-graylog
tags:
  install-elasticsearch: false
  install-mongodb: false
```

Looking at the service logs IP Address should be a public IP and not private.

`Error syncing load balancer: failed to ensure load balancer: findMatchedPIPByLoadBalancerIP: cannot find public IP with IP address 10.224.2.5 in resource group mc_loggi_group_logging_northeurope`
